### PR TITLE
Added plain ValidationAttribute for model-based validation

### PR DESCRIPTION
**Pull request by Atrejoe**
For simple non-MVC Web API clients

### CODE REVIEW

**Comment by TimothyMeadows** [comment]
What is the purpose of this?

**Comment by Atrejoe** [comment]
It re-uses the validation logic without using the form-generating logic.
In my case I have a plain Web API that is being used by an (Angular) client.

Attribute-based validation is used, and it would be nice if Captcha input can be validated in the same way.

**Comment by Atrejoe** [comment]
```csharp
/// <summary>
/// Performs password recovery request.
/// </summary>
/// <returns>A status code only.</returns>
/// <response code="200">User is known and password recovery request has been initiated <br/>
/// or
/// <br/>
/// user is not known (not exposing account stataus to unaiuthenticated users).</response>
/// <response code="400"><paramref name="emailAddress"/> or <paramref name="captchaCode"/> were not specified or invalid.</response>
[HttpPost]
[Route("password")]
[ActionName("resetrequest")]
[AllowAnonymous]
[ProducesResponseType(StatusCodes.Status200OK)]
[ProducesResponseType(StatusCodes.Status400BadRequest)]
public async Task<StatusCodeResult> ResetPassword(
	[Required, EmailAddress] string emailAddress,
	[Required, CaptchaResponse] string captchaCode) {

	//do logic here: in this case send a password recovery email when the accounts exists

	return Ok();
}
```

**Comment by TimothyMeadows** [comment]
Merged, will test this weekend for nuget update.

**Pull request merged**
